### ISSUE TITLE
How to finetune the reconstruction network with the render code and provided pd model

### ISSUE THREAD

**Issue by hjy1312** [sicxu/Deep3dPortrait#16]

**Comment by sicxu** [comment]
Could you provide more details about your question? There is no finetune step in 3d head reconstruction.

**Comment by hjy1312** [comment]
@sicxu I am trying to finetune the network which produces the 3DMM coefficients to fit another 3DMM statistical model.  But I'm stuck in reconstructing the face images with the estimated face shape, face texture and illumination.  In addition, the provided model seems to be only used for testing. Could you please offer more details? Many thanks.

**Comment by sicxu** [comment]
Yes, our released face reconstruction model is only for testing. If you want to use our pretrained model for finetuing, you need to reimplement the full network and load our pb file as inital weight.  We have detailed the network structure in our supplementary material and our another paper [Accurate 3D Face Reconstruction with Weakly-Supervised Learning: From Single Image to Image Set](https://arxiv.org/abs/1903.08527). You can also refer to [Deep3DFaceReconstruction](https://github.com/microsoft/Deep3DFaceReconstruction) for more details.
Also, since you want to fit another 3DMM statistical model, you need to change the last fc to match the dimension of your 3DMM's coefficients.
