### ISSUE TITLE
about the result with neck

### ISSUE THREAD

**Issue by MontaEllis** [sicxu/Deep3dPortrait#23]
Hi, now I want a result with neck and I have got the right model. However, its color has some deviation. What should I do to solve this problem? Should I change the landmark standard?
![图片](https://user-images.githubusercontent.com/37856372/100267946-3fac0900-2f8f-11eb-93ca-031b0bb23c32.png)

**Comment by sicxu** [comment]
The result you provided seems to be opposite to the right view. (see the following example.)
![image](https://user-images.githubusercontent.com/64250193/100310363-fb008c00-2fe7-11eb-945e-f3f8c43538c4.png)
Besides,  since our results are based on the cropped face model, could u provide more info about the neck part in your result?
