### ISSUE TITLE
Do you have pre-trained models for face segmentation

### ISSUE THREAD

**Issue by cravisjan97** [sicxu/Deep3dPortrait#6]
I noticed that in the README, you mentioned the ROI-tanh work (https://github.com/Eskender-B/roi-tanh). But their repository does not have any links to their pre-trained models for face segmentation. Is it possible for you to share your pre-trained models for face segmentation?

Thanks in advance!

**Comment by sicxu** [comment]
1. The repo you mentioned is not an offical implementation. 
2. Sorry, we can not share our pre-trained face segmentation model. You may implement it following Lin et al.'s paper.
3. For #7 ,  there are two ways to obtain the segmentation masks aligned with raw image. You can feed the cropped image to the segmentation network and realign the results with raw images. Or, you can follow [Lin et al.'s method](https://arxiv.org/pdf/1906.01342.pdf) as we do. They applied a tanh-warping for input images. For more details please refer to their paper.

**Comment by cravisjan97** [comment]
For #7 you mentioned realigning the results with raw images. Are there any algorithms to do this?

**Comment by sicxu** [comment]
Since we applied a transform to obtain the cropped image, we can easily apply the corresponding inverse transform to the cropped image/mask to restore the original image. Anyway, I have uploaded a simple func for your purpose.
https://github.com/sicxu/Deep3dPortrait/blob/fad83d78cea303eb3da24afd59fac960eb3f6f38/restore_from_crop.py#L8

**Comment by cravisjan97** [comment]
@sicxu Thanks for the reply!!!
